# Generated by Django 6.0.7 on 2026-08-12 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse de résidence')),
                ('city', models.CharField(default='Kalemie', max_length=100, verbose_name='Ville')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Quartier / Avenue')),
                ('bio', models.TextField(blank=True, verbose_name='Présentation & Expériences')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name="Années d'expérience")),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('BUSY', 'Occupée'), ('INACTIVE', 'Inactive / Suspendue')], default='AVAILABLE', max_length=10, verbose_name='Statut')),
                ('is_verified', models.BooleanField(default=False, verbose_name="Vérifiée par l'agence")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services', models.ManyToManyField(blank=True, related_name='cleaners', to='services.service', verbose_name='Services maîtrisés')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cleaner_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Ménagère',
                'verbose_name_plural': 'Profils Ménagères',
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], verbose_name='Jour de la semaine')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='cleaners.cleanerprofile', verbose_name='Ménagère')),
            ],
            options={
                'verbose_name': 'Disponibilité',
                'verbose_name_plural': 'Disponibilités',
                'unique_together': {('cleaner', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
